DataCoreSoftware/ZFSin

- ZFSin/driver.c
- ZFSin/zfs/module/zfs/zfs_vnops_windows.c
- ZFSin/zfs/module/zfs/zfs_vnops_windows_mount.c
- ZFSin/zfs/module/zfs/zfs_windows_zvol.c
- ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c
Apply comment from pull request: https://github.com/DataCoreSoftware/ZFSin/pull/1
related with changes in Jira's:
http://jira/browse/SSV-17628 - BSOD ZFSin!spl_get_or_create_hostid+0xdb
http://jira/browse/SSV-17666 - BSOD ZFSin!ZFSin!CreateReparsePoint+13b
http://jira/browse/SSV-17778 - Root cause analysis of BSOD-ZFSin!dispatcher+0x38
> Stabilization

- ZFSin/zfs/module/zfs/vdev_disk.c
- ZFSin/zfs/module/zfs/vdev_file.c
- ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c
Important fixes went in upstream/master, particularly the MDL leak fix.
> updating from upstream/master

- ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c
Problem: the pool driver can sometimes issue I/Os through the DI at DISPATCH level from a DPC routine.
Reason: That causes taskq queuing to BSOD because of a mutex used in the taskq mechanism.
Fix: Return to using a workitem to queue a request that will then queue the I/O in the taskq.  Do it for all I/Os, even when running at a level < DISPATCH because we want to return control to the caller as soon as possible and do not want to suffer being preempted by the wait on the taskq mutex.
also aligned the workitem block on a 16-bytes boundary: this is preferable as it is the standard alignment for dynamic memory allocations on a x64 system.
TESTED: Verified on my rig.  QA will re-rerun the TP closedown tests and that will be enough.
> SSV-19147 - BSOD in ZFSin due to high IRQL

- ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c
Problem: a mutex is taken in the uio_xxxx routines and BSOD the system when DcsPool calls in the DI at DISPATCH level.
Reason: A lot of ZFS routines rely on mutexes instead of spinlocks.  It is fine for DcsPool to be calling in at DISPATCH but ZFS must handle it by not using any of those routines.
Fix: Always queue a workitem, do all the work there and always return STATUS_PENDING to the DI client (i.e.DcsPool). That will take care of all cases now.
TEST: Performed basic VD test with I/O running through the DI.  
QA has to run the same regression test as for SSV-19147 , since this issue was found during that regression test.
> ssv-19161 - BSOD: ZFSin!uio_create+0x2f invoked at DISPATCH from DcsPool

- ZFSin/zfs/include/sys/metaslab_impl.h
- ZFSin/zfs/module/zfs/metaslab.c
This will be useful for tracking metaslab thrashing
Signed by: Yash Jain <yash.jain@datacore.com>
> New kstat module zfs_metaslab_stats

- ZFSin/zfs/module/zfs/dbuf.c
- ZFSin/zfs/module/zfs/dsl_dir.c
- ZFSin/zfs/module/zfs/vdev.c
- ZFSin/zfs/module/zfs/vdev_removal.c
- ZFSin/zfs/module/zfs/zap_micro.c
- ZFSin/zfs/module/zfs/zfs_ioctl.c
- ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c
- ZFSin/zfs/module/zfs/zil.c
- ZFSin/zfs/module/zfs/zvol.c
- zfsinstaller/zfsinstaller.cpp
Changed the min and max buffer count for logman session to 1.
Changed the buffer size to 1KB for logman session
> Add logging information to zpool remove command.

- ZFSin/spl/module/spl/spl-kmem.c
- ZFSin/spl/module/spl/spl-vmem.c
> Periodically calling 'vmem_update' function to dynamically update the vmem->vm_hash_table size.

- ZFSin/zfs/cmd/zdb/zdb.c
Fix for **zdb -R** command for various flags.
> Fix for zdb -R command

- ZFSin/OpenZFS.man
- ZFSin/zfs/cmd/zdb/zdb.c
- ZFSin/zfs/include/sys/zfs_ioctl.h
- ZFSin/zfs/module/zfs/zfs_ioctl.c
zpool counters (Active/Pending Reads/Writes) added to perfmon
> zpool counters (Active/Pending Reads/Writes) added to perfmon

- ZFSin/zfs/include/sys/zfs_ioctl.h
- ZFSin/zfs/lib/libefi/rdwr_efi.c
- ZFSin/zfs/module/zfs/zfs_ioctl.c
- ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c
Fix zpool stats ioctl to take targetid and lun as input
> Fix zpool stats ioctl to take targetid and lun as input

- ZFSin/zfs/module/zfs/zfs_windows_zvol.c
- test/vdbench-Automation/Lib/VdBenchLib/execution.py
Fix reclamation code to consider zvol reclamation done in dcspool
> Fix reclamation code to consider zvol reclamation done in dcspool

- test/vdbench-Automation/Lib/VdBenchLib/execution.py
Disabling Capacity Optimization using PowerShell and setting ashift=12 for SLOG and L2ARC
> Disabling Capacity Optimization using PowerShell and setting ashift=12 for SLOG and L2ARC

- ZFSin/OpenZFS.man
- ZFSin/zfs/cmd/zpool/zpool_main.c
- ZFSin/zfs/include/sys/zfs_ioctl.h
- ZFSin/zfs/module/zfs/zfs_ioctl.c
- test/vdbench-Automation/Lib/VdBenchLib/execution.py
Exporting 'zpool iostat latency' stats to perfmon
> Exporting 'zpool iostat latency' stats to perfmon

- test/vdbench-Automation/Lib/VdBenchLib/vdbench.py
Fixing previous PR change which broke result HTML file of vdbench
> Fixing previous PR change which broke result HTML file of vdbench

- ZFSin/zfs/cmd/zpool/zpool_vdev.c
- ZFSin/zfs/module/zfs/spa.c
- ZFSin/zfs/module/zfs/vdev.c
- ZFSin/zfs/module/zfs/vdev_file.c
- ZFSin/zfs/module/zfs/vdev_label.c
- ZFSin/zfs/module/zfs/vdev_removal.c
- ZFSin/zfs/module/zfs/zfs_ioctl.c
- test/vdbench-Automation/Lib/VdBenchLib/vdbench.py
added logs to help root-cause the occasional failure in vdev removal when L2ARC & SLOG are configured
> added logs to help root-cause the occasional failure in vdev removal when L2ARC & SLOG are configured

- ZFSin/OpenZFS.man
- ZFSin/spl/include/sys/kstat.h
- ZFSin/spl/module/spl/spl-kstat.c
- ZFSin/zfs/include/sys/zfs_ioctl.h
- ZFSin/zfs/module/zfs/zfs_ioctl.c
Cache counters are ARC, L2ARC, ZIL, and SLOG.
> Cache counters added to perfmon

- ZFSin/spl/module/spl/spl-windows.c
- ZFSin/zfs/module/zfs/arc.c
- ZFSin/zfs/module/zfs/zvol.c
Removed unwanted global variable 'total_physical_memory' which is same as 'real_total_memory'
> Removed unwanted global variable 'total_physical_memory' which is same as 'real_total_memory'

- Tools/DedupEstimationTool/DcsEstimateDedupRatio.py
- Tools/DedupEstimationTool/config.py
- Tools/DedupEstimationTool/disk_scan.py
- Tools/DedupEstimationTool/file_scan.py
Dedup Estimation Tool creation
> Dedup estimation tool

- ZFSin/spl/include/sys/kmem.h
- ZFSin/spl/include/sys/systm.h
- ZFSin/spl/include/sys/vmem.h
- ZFSin/spl/module/spl/spl-kmem.c
- ZFSin/spl/module/spl/spl-vmem.c
- ZFSin/spl/module/spl/spl-windows.c
https://dcsw.atlassian.net/browse/ZFS-1136.
Merged the changes from the fix in Openzfs 2.0
> Cancel the bsd-timers before driver unload

- test/vdbench-Automation/Config/VdBench_config/VDBench_config.ini
- test/vdbench-Automation/Lib/VdBenchLib/execution.py
- test/vdbench-Automation/Lib/VdBenchLib/vdbench.py
- test/vdbench-Automation/TestSuite/PerformanceTests/VDBench/TestSuite.py
- Updated Mirror Special Device REST API url
- Added disk types ildce/ilde/ilce/encrypted/unencrypted to support changes for Hybrid ILDC
- Added unencrypted disk type to support the runs for previous PSP versions
> TA-6421: VDbench automation changes for Hybrid ILDC

- test/vdbench-Automation/Config/VdBench_config/VDBench_config.ini
- test/vdbench-Automation/HTML_Template/VdBench_Template.html
- test/vdbench-Automation/Lib/VdBenchLib/execution.py
- test/vdbench-Automation/Lib/VdBenchLib/vdbench.py
- test/vdbench-Automation/TestSuite/PerformanceTests/VDBench/TestSuite.py
- Added set_zvolsize() which sets zvols size to custom size or default size.
- Made changes in Reporting for adding zvol size in Configuration table
- Changed Oracle and SQL index in reporting
> TA-6644: Changes to customize zvol size
