DataCoreSoftware/ZFSin

ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c
Problem: For zvols of size 8GB (and above), we begin to see writes and reads miscompare.
Cause: Offsets can go beyond 32 bits for a large zvol. We were using ULONG for storing and manipulating the offsets.
Fix: Use ULONGLONG instead of ULONG for startingSector and sectorOffset variables.
=> Fix for miscompare issue

ZFSin/zfs/lib/libspl/posix.c
problem: When the hostid value is not yet defined in the registry the library throws an assertion sometimes while trying to import the pool.
reason: the value type is not initialized in the stack so when the registry call fails to get the hostid the type value is still compared to REG_DWORD.
fix: do not check for possible assertion on the value type if the call failed.
=> Fixed wrong assertion in libspl

ZFSin/zfs/lib/libspl/posix.c, ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c
problem: It was possible for a DI request to be failed before being queued up for processing in the ZFS driver. when this happened the pool driver would never get its IRP completion routine called.
fix: if the I/O processing is failed in ZFS prior to queuing to the I/O, added the call for the DI callback to run.
Once the I/O is processed by the queuing mechanism it will always call the DI callback.
=> zfs-207 - ensure completion routine call during DI failures

ZFSin/driver.c, ZFSin/spl/module/spl/spl-kmem.c, ZFSin/zfs/include/sys/kstat_windows.h, ZFSin/zfs/module/zfs/zfs_kstat_windows.c
Allow the user to set 'zfs_total_memory_limit' as long as it is in the range 2GB to total_memory (total_memory is currently 50% of total RAM).
=> zfs_total_memory_limit registry entry

ZFSin/zfs/module/zfs/metaslab.c, ZFSin/zfs/module/zfs/vdev_removal.c
1. Fixed memory corruption in 'metaslab_unload' due to
'metaslab_group_passivate' function not setting the freed pointer to
NULL.
2. Fixed '.\zfsinstaller.exe uninstall .\ZFSin\ZFSin.inf' command hang
after zpool removal due to 'spa_vdev_remove_thread' not calling
'thread_exit()' during exit.
=> ZFSin crash on zpool remove

ZFSin/ZFSin.vcxproj, ZFSin/ZFSin.vcxproj.filters, ZFSin/zfs/cmd/zdb/zdb/zdb.vcxproj, ZFSin/zfs/cmd/zfs/zfs/zfs.vcxproj, ZFSin/zfs/cmd/zpool/zpool/zpool.vcxproj, ZFSin/zfs/cmd/zstreamdump/zstreamdump/zstreamdump.vcxproj, ZFSin/zfs/include/sys/abd.h, ZFSin/zfs/module/icp/include/modes/modes.h, ZFSin/zfs/module/icp/include/sys/crypto/aes_gcm.h, ZFSin/zfs/module/icp/io/aes.c
1. Integrated ISA-L encryption aes-256-gcm to ZFSin  
If the cpu supports avx feature we call the ISA-L  version of aes-256-gcm.
2. Added isa-l_crypto_static.lib to ZFSin
3. Added 'aes_gcm.h' header file to ZFSin, this is required for ISA-L
=> Integrate AES-256-GCM from ISA-L crypto

ZFSin/zfs/include/sys/dsl_pool.h, ZFSin/zfs/include/sys/kstat_windows.h, ZFSin/zfs/module/zfs/dsl_pool.c, ZFSin/zfs/module/zfs/txg.c, ZFSin/zfs/module/zfs/zfs_kstat_windows.c
With zfs_dirty_data_sync too-frequent TXG sync causes excessive write  inflation, so removed 'zfs_dirty_data_sync' config and added 'zfs_dirty_data_sync_percent' which is set to 20% of 'zfs_dirty_data_max'.
=> Port 'zfs_dirty_data_sync_percent' change from Linux

ZFSin/zfs/include/sys/zfs_ioctl.h, ZFSin/zfs/include/sys/zfs_windows.h, ZFSin/zfs/module/zfs/zfs_ioctl.c, ZFSin/zfs/module/zfs/zfs_vnops_windows.c
Given a zpool name, the API returns allocated space and total size of zpool
=> Adding zpool API to retrieve allocated and total size of a zpool

ZFSin/OpenZFS.man, ZFSin/zfs/include/sys/zfs_ioctl.h, ZFSin/zfs/module/zfs/zfs_ioctl.c
Added the _Total instance to OpenZFS zpool.
Changed the unit of metrics from MBytes/sec to Bytes/sec.
Changed type of counter from perf_counter_counter to perf_counter_bulk_count to accommodate 64 bit values
=> Add _Total instance for OpenZFS zpool Counterset

ZFSin/OpenZFS.man, ZFSin/zfs/include/sys/zfs_ioctl.h, ZFSin/zfs/module/zfs/zfs_ioctl.c
Added counters : 
- Active_Sync_Reads          
- Active_Sync_Writes 
- Active_Async_Reads 
- Active_Async_Writes 
- Pend_Sync_Reads 
- Pend_Sync_Writes 
- Pend_Async_Reads 
- Pend_Async_Writes
=> zpool counters added to perfmon

ZFSin/zfs/module/zfs/zfs_windows_zvol.c
By changing 'NumberOfPhysicalBreaks=0x21' we are able to improve ZFSin performance by 50%.
Default 'NumberOfPhysicalBreaks' is set to 0x11, that is 64K, so for every 128K read/write storport will send two request to ZFSin, now changing the value to 0x21 reduced the number of request by half and thus improving the performance.
Also we can see that the  performance is now exactly matching with the Linux performance.
```
Windows:
---------------------------------------------------------------------------------------------------------------------------------------
Disk Type				Operation	block-size	threads		i/o       MB/sec    queue  cpu%    cpu%	   
(vdbench)			rate      1024**2   depth  sys+u   sys	   
------------------------------------------------------------------------------------------- …
```
=> ZFSin set NumberOfPhysicalBreaks = 0x21 this will make zvol perform better when the blockssize is >=128K

ZFSin/OpenZFS.man, ZFSin/zfs/cmd/zpool/zpool_main.c, ZFSin/zfs/include/sys/zfs_ioctl.h, ZFSin/zfs/module/zfs/zfs_ioctl.c
To fetch the average latency values for respective read and write (total_wait, disk_wait, async_wait, sync_wait), we need to calculate (wait_time/wait_count).
=> Exporting 'zpool iostat latency' stats to perfmon

ZFSin/driver.c, ZFSin/spl/module/spl/spl-windows.c, ZFSin/zfs/module/zfs/arc.c
Added support for setting/reading 'zfs_total_memory_limit' using kstat command. Now without a system reboot we can increase the zfs_total_memory_limit, decreasing the values need a reboot.
=> Reading and setting 'zfs_total_memory_limit' is moved to 'spl_start' routine

ZFSin/zfs/module/zfs/zfs_ioctl.c, ZFSin/zfs/module/zfs/zio.c
Fixed ZFSin going to an infinate loop when the underlying disk returns error.
Also fixed 'zpool clear' command not working on ZFSin.
=> Fixed ZFSin going to an infinate loop when the underlying disk returns error

ZFSin/zfs/module/zfs/zil.c
Ideally the application should get an error or wait until the admin
fixes the disk error and run 'zpool clear' command. But without this
fix ZFSin was returning success even when the write failed.
Jenkins test result
http://10.200.0.86:8080/job/ZFS-Test-Suite/52/console
=> Fixed data miscompare issue when the backend disk returns error to ZFSin

ZFSin/ZFSin.vcxproj, ZFSin/zfs/module/zfs/zfs_vnops_windows.c, ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c, ZFSin/zfs/module/zfs/zvol.c
SSV-20428: One of the ZVOL failed after a RestartSSV while running HA-DCAF tests
https://dcsw.atlassian.net/browse/SSV-20428
Changes
SSY failed to get DI interface for the failed zvol. Added additional debug logs which could help if issue is reproduced again.
Added additional logs for files:-
ZFSin/zfs/module/zfs/zfs_vnops_windows.c
ZFSin/zfs/module/zfs/zfs_windows_zvol_scsi.c
ZFSin/zfs/module/zfs/zvol.c
ZFSin/ZFSin.vcxproj:-
WPP tracing was disabled for file 'zfs_vnops_windows.c' as it creates much noise using dprintf(). So added new couple of logs 
using TraceEvent() functions. Now enbaled tracing only for TraceEvent() which was not used in this file earlier.
=> ssv-20428-addedlogs-dcaf-zvol-failed-issue

ZFSin/zfs/module/zfs/zvol.c
Assign the targetid and Lun for zvol after it is fully open.
=> Assign the targetid for zvol after it is fully open

ZFSin/zfs/module/zfs/zfs_windows_zvol_wmi.c
Jira:- https://dcsw.atlassian.net/browse/SSV-20352
Issue:- The GetDiscoveredPortAttributes() WMI method was not implemented for the WMI class MSFC_HBAAdapterMethods. This was causing problem with SCVMM setup in customer environment.
Fix:- Implemented the default method for the WMI class. Returning the status as 'HBA_STATUS_ERROR_ILLEGAL_INDEX'(=6) because it was the status returned by the other FC adapter driver in the customer environment. ZFSin as a virtual driver does not support this functionality.
To Test:- Execute the below WMI query from Powershell and it should not return any error.
Get-WMIObject -Class MSFC_HBAAdapterMethods -Namespace root\wmi | ForEach-Object {$_.GetDiscoveredPortAttributes(0,0)}
=> ssv-20352 Handled WMI method GetDiscoveredPortAttributes

ZFSin/zfs/module/zfs/zfs_windows_zvol_wmi.c
Jira:- https://dcsw.atlassian.net/browse/SSV-20352
Issue:- The GetDiscoveredPortAttributes() WMI method was not implemented for the WMI class MSFC_HBAAdapterMethods. This was causing problem with SCVMM setup in customer environment.
Fix:- Implemented the default method for the WMI class. Returning the status as 'HBA_STATUS_ERROR_ILLEGAL_INDEX'(=6) because it was the status returned by the other FC adapter driver in the customer environment. ZFSin as a virtual driver does not support this functionality.
To Test:- Execute the below WMI query from Powershell and it should not return any error.
Get-WMIObject -Class MSFC_HBAAdapterMethods -Namespace root\wmi | ForEach-Object {$_.GetDiscoveredPortAttributes(0,0)}
=> Merge ssv-20352 changes (from master) into psp12u1

ZFSin/zfs/lib/libefi/rdwr_efi.c
Zpool create fails on Windows 2016 server with the error ""cannot label <DRIVE>: unable to read disk capacity".
https://dcsw.atlassian.net/browse/ZFS-1013 
Merging below commit from psp14 branch. 
https://github.com/DataCoreSoftware/ZFSin/pull/64/commits/366697628614f703569903fbdcd8c712872146f1
=> Fix error message "cannot label <DRIVE>: unable to read disk capacity"
